// 🆘 SOS LOGIC
// ============================================
const sosSteps = [{n:5,t:'ВЕЩЕЙ',d:'Найди 5 предметов одного цвета'},{n:4,t:'ОЩУЩЕНИЯ',d:'Почувствуй 4 касания'},{n:3,t:'ЗВУКА',d:'Услышь 3 звука вокруг'},{n:2,t:'ЗАПАХА',d:'Почувствуй 2 аромата'},{n:1,t:'ВКУС',d:'Ощути 1 вкус'}];
let sosIdx = 0;
function resetSos() { sosIdx = 0; const c = document.getElementById('sos-content-area'); if(c) c.innerHTML = ''; const d = document.getElementById('sos-desc-area'); if(d) d.innerHTML = ''; const btn = document.getElementById('sos-main-btn'); if(btn) { btn.querySelector('span').innerText = 'Я НАШЕЛ'; btn.onclick = nextSos; } }
function startSos() { renderSosStep(); }
function renderSosStep() { const s = sosSteps[sosIdx]; const content = document.getElementById('sos-content-area'); if(!content) return; content.innerHTML = ''; const numDiv = document.createElement('div'); numDiv.className = 'sos-big-number'; numDiv.innerText = s.n; numDiv.style.animation = 'pop-up-letter 0.5s ease forwards'; content.appendChild(numDiv); const textLine = document.createElement('div'); textLine.className = 'sos-text-line'; s.t.split('').forEach((char, index) => { const span = document.createElement('span'); span.className = 'sos-letter'; span.innerText = char; span.style.animation = `pop-up-letter 0.4s ease forwards`; span.style.animationDelay = `${0.2 + (index * 0.05)}s`; textLine.appendChild(span); }); content.appendChild(textLine); const desc = document.getElementById('sos-desc-area'); desc.className = 'sos-desc'; desc.innerText = s.d; desc.style.animation = 'none'; desc.offsetHeight; desc.style.animation = 'fadeIn 0.5s ease forwards 0.5s'; const btn = document.getElementById('sos-main-btn'); btn.classList.remove('sos-btn-enter'); void btn.offsetWidth; btn.classList.add('sos-btn-enter'); }
function nextSos() { if(tg.HapticFeedback) tg.HapticFeedback.impactOccurred('medium'); if (sosIdx < sosSteps.length - 1) { sosIdx++; renderSosStep(); } else { document.getElementById('sos-content-area').innerHTML = `<span class="material-icons-round" style="font-size:100px;color:var(--primary-main);animation:pop-up-letter 0.6s forwards;">check_circle</span><div class="sos-text-line" style="margin-top:20px;color:var(--text-header)">ТЫ МОЛОДЕЦ</div>`; document.getElementById('sos-desc-area').innerText = 'Ты справился. Дыши спокойно.'; const btn = document.getElementById('sos-main-btn'); btn.querySelector('span').innerText = 'В МЕНЮ'; btn.onclick = goBack; btn.classList.remove('sos-btn-enter'); void btn.offsetWidth; btn.classList.add('sos-btn-enter'); if(tg.HapticFeedback) tg.HapticFeedback.notificationOccurred('success'); checkAchievements(); } }

function sendUserIdToServer() { if (userId.toString().startsWith('test_')) return; const startParam = tg.initDataUnsafe?.start_param || ''; const referrerId = startParam.startsWith('ref_') ? startParam.replace('ref_', '') : null; fetch(GOOGLE_SCRIPT_URL + '?act=api', { method: 'POST', body: JSON.stringify({ action: 'user_joined', initData: tg.initData, referrerId: referrerId }) }).then(r=>r.json()).then(d => { if (d.balance !== undefined) updateLocalBalance(d.balance); }).catch(e => {}); }

// ============================================
